openapi: 3.0.0
info:
  title: Sonnenlicht
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Properties
  - name: Users
  - name: Auth
paths:
  /properties:
    get:
      tags:
        - Properties
      summary: Get All Properties
      security:
        - noauthAuth: []
      parameters:
        - name: token
          in: header
          schema:
            type: string
          example: '{{token}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                - price: 420000
                  title: Title
                  offerType: sell
                  propertyType: small house
                  addressLocation: location
                  addressNumber: 420
                  addressStreet: street
                  ownerId: id
                - price: 420000
                  title: Title 2
                  offerType: sell
                  propertyType: small house
                  addressLocation: location
                  addressNumber: 420
                  addressStreet: street
                  ownerId: id
  /my-properties:
    get:
      tags:
        - Properties
      summary: Get My Properties
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                - price: 420000
                  title: Title
                  offerType: sell
                  propertyType: small house
                  addressLocation: location
                  addressNumber: 420
                  addressStreet: street
                - price: 420000
                  title: Title
                  offerType: sell
                  propertyType: small house
                  addressLocation: location
                  addressNumber: 420
                  addressStreet: street
  /property/{id}:
    get:
      tags:
        - Properties
      summary: Get Property
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                price: 420000
                title: Title
                offerType: sell
                propertyType: small house
                addressLocation: location
                addressNumber: 420
                addressStreet: street
                ownerId: id
  /property-owner/{propertyId}:
    get:
      tags:
        - Properties
      summary: Get Owner
      security:
        - noauthAuth: []
      parameters:
        - name: propertyId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                ownerId: id
  /approve/{id}:
    patch:
      tags:
        - Properties
      summary: Approve Property
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: null
  /reject/{id}:
    patch:
      tags:
        - Properties
      summary: Reject Property
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: null
  /retry/{id}:
    patch:
      tags:
        - Properties
      summary: Retry
      requestBody:
        content: {}
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: null
  /new-property:
    post:
      tags:
        - Properties
      summary: Create Offer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                price: 420000
                title: Title
                offerType: sell
                propertyType: small house
                addressLocation: location
                addressNumber: 420
                addressStreet: street
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                type: string
              example: null
  /user/{id}:
    patch:
      tags:
        - Users
      summary: Change User Role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                role: admin
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example: {}
    delete:
      tags:
        - Users
      summary: Delete User
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: null
    put:
      tags:
        - Users
      summary: Edit User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phoneNumber: '99999999'
                name: test
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                email: email@test.com
                phoneNumber: '99999999'
                name: test
                role: owner
    get:
      tags:
        - Users
      summary: Get User
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                email: email@test.com
                phoneNumber: '99999999'
                name: test
                role: owner
  /users:
    get:
      tags:
        - Users
      summary: Get All Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                - email: email2@test.com
                  phoneNumber: '99999999'
                  name: test
                  role: owner
                - email: email2@test.com
                  phoneNumber: '99999999'
                  name: test2
                  role: owner
  /register:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: email@test.com
                password: test
                phoneNumber: '99999999'
                name: test
                role: owner
      security:
        - noauthAuth: []
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                type: string
              example: null
  /auth:
    post:
      tags:
        - Auth
      summary: Authenticate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: email@email.test
                paswword: example
      security:
        - noauthAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                token: some_JWT
